name: Update Activity Graph

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Generate Activity Graph
        uses: maurodesouza/github-readme-activity-graph-action@v1
        with:
          username: sr-exe
          options: >-
            bg_color=050505&
            color=FF3B3B&
            title_color=FF3B3B&
            line=FF3B3B&
            point=FFFFFF&
            area_color=4A0000&
            area=true&
            hide_border=true&
            custom_title=Shubham's%20GitHub%20Activity
          output_path: dist/activity-graph.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Activity Graph
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          build_dir: dist
          target_branch: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
